### ISSUE TITLE
[1.12.2] NameTags/PlayerList have the wrong color

### ISSUE THREAD

**Issue by RaphiMC** [Earthcomputer/multiconnect#140] opened 2021-01-13 12:39 UTC
Used multiconnect version: 1.3.34 for 1.16.4
Servers native version is 1.8
Used protocol version in multiconnect: 1.12.2 (Video compares to 1.12.2 client)
Server: MineSucht.net
Steps to reproduce: Watch the video

Issue: Player names (also applies to tablist player names) have wrong color (can be seen at 00:29) (both players should have the same color as both aren't in any team). Maybe related to #133 

Video that shows all the bugs: https://streamable.com/yfiy3r

**Comment by Earthcomputer** [comment] 2021-01-13 13:01
Duplicate of #133

**Closed by Earthcomputer** 2021-01-13 13:01 UTC
