### ISSUE TITLE
Players unable to join "LAN" world

### ISSUE THREAD

**Issue by Shroototem** [Earthcomputer/multiconnect#92] opened 2020-08-27 03:43 UTC
If you use the /publish command with port-forwarding, players are not able to join the world. 
Version: 1.16.2
MultiConnect 1.3.14

**Comment by Earthcomputer** [comment] 2020-08-27 07:45
You are three versions out of date, please update to the latest version of multiconnect and tell me if it still happens

**Comment by Earthcomputer** [comment] 2020-08-31 10:29
Cannot reproduce. I didn't test with port forwarding but I doubt that would make a difference. Are players joining on the correct version? Multiconnect doesn't do serverside translation
![Screenshot from 2020-08-31 11-27-50](https://user-images.githubusercontent.com/13084089/91711063-2c022980-eb7d-11ea-8711-cf0f37c4a2a1.png)

**Comment by Shroototem** [comment] 2020-08-31 11:10
I'm sorry about not responding for a while. I haven't had others to test that issue. The latest version seems to not allow me to join a paper server that allows 1.8-1.13
However I want to test without any other mods installed to make sure.

**Comment by Earthcomputer** [comment] 2020-08-31 11:18
Hm, you should be able to connect with the 1.11, 1.12 or 1.13 protocol, although you may have to explicitly set the protocol (it's impossible to auto-detect).

**Comment by Shroototem** [comment] 2020-08-31 11:21
I tested it with all versions in-between and when I dropped back down to the version I had it was working.

**Comment by Earthcomputer** [comment] 2020-08-31 11:23
Is this a public server? If so, what is the IP? If it's a private server, what version bridge do you have?

**Comment by Shroototem** [comment] 2020-08-31 11:28
play.thebaddeveloper.tech
I'll have to get you whitelisted but I can message you when you are.

**Comment by Shroototem** [comment] 2020-08-31 15:03
Sorry but the server I was testing with is changing constantly which is not helpful... They're still in development. I'll do more tests and get back to you.

**Comment by Username404-59** [comment] 2020-08-31 20:16
@Shroototem So you're playing on a server, or on a LAN server?

**Comment by Shroototem** [comment] 2020-08-31 20:36
> @Shroototem So you're playing on a server, or on a LAN server?

LAN server with the port open.

**Comment by Shroototem** [comment] 2020-08-31 21:00
The issue seems to have been server-side and they fixed it. ( Plugin servers... Yuck )
About the /publish command, I really don't have others to help me test it. I just noticed it wasn't working properly and I'm assuming it's working properly in the newest version.

**Comment by Earthcomputer** [comment] 2020-08-31 21:11
I guess that's problem resolved? We can close this then.

**Closed by Earthcomputer** 2020-08-31 21:11 UTC
