### ISSUE TITLE
Item texture error.

### ISSUE THREAD

**Issue by plusls** [Earthcomputer/multiconnect#125] opened 2020-11-09 08:45 UTC
![image](https://user-images.githubusercontent.com/23459592/98517376-cdf27080-22a8-11eb-89f7-b62c3d5c4e42.png)
![image](https://user-images.githubusercontent.com/23459592/98517423-da76c900-22a8-11eb-8278-0bcd10688db8.png)
![image](https://user-images.githubusercontent.com/23459592/98517567-10b44880-22a9-11eb-88ff-9bf9eb076907.png)

First I connect to an 1.16.1 fabric server,  multiconnect work normally. After that I start singleplay, all item texture  shuffled.

1.16.1 server with [gravestone mod](https://github.com/uestclug/gravestone), it register `gravestone block` in server but cheat client that it is a player skull.

server address: beta.uestc.dev

**Comment by Earthcomputer** [comment] 2020-11-09 12:38
> it register `gravestone block` in server but cheat client that it is a player skull

You mean it "tells" the client, not "cheats" it? You almost had me insta-close this for cheat clients then.

Anyway, that sounds fishy, multiconnect is supposed to disconnect you when the server registry has been modified at all. Maybe it has something to do with that, I'll have to check exactly what the gravestone mod is doing. But I've had this happen after connecting to vanilla servers too, no idea what the cause is.

**Comment by plusls** [comment] 2020-11-09 14:00
In the case of the same version, fabric will send CustomPayloadC2SPacket to sync the block id registry. But in the case of different versions, the CustomPayloadC2SPacket of fabric is blocked, so it can connect to the server directly. As for `cheat`, it is because I originally intended to prevent the block synchronization behavior of the fabric, because the gravestone block has not texture, and the server tell the client that this is a vanilla `skull block` instead of a `gravestone block`.

**Comment by ZuccySuccy** [comment] 2020-11-27 01:55
I can personally confirm that the gravestone mod does not cause this issue. It is simply an issue with multiconnect. I have connected to a fabric server with just multiconnect and loaded into a singleplayer world with this same issue. I don't exactly see why this is marked as low priority as it makes playing the game borderline impossible without restarting the game.

**Comment by plusls** [comment] 2020-11-27 03:22
I only know that i can reproduce this bug via gravestone mod. For developers, a way to stably reproduce bugs is very important.

**Comment by Earthcomputer** [comment] 2021-01-22 12:36
Again, if anyone can find a reliable way of reproducing this issue, it will be much easier for me to take a look at it

**Comment by Pairman** [comment] 2021-01-26 12:53
This bug always occurs in my client(1.15.2), even when single player. Sometime when I open my inevntory and scroll to some item, the games crashes. Maybe because the game failed to show two textures mapped from the single object.

**Closed** 2022-07-07 21:52 UTC
Labels: bug, priority: low, registry refactor
