### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by trolle6** [Earthcomputer/multiconnect#219] opened 2021-08-07 22:43 UTC
[latest.log](https://github.com/Earthcomputer/multiconnect/files/6949966/latest.log)

joined a 1.16.5 server on a 1.17.1 client got kicked this is what i got

**Comment by Earthcomputer** [comment] 2021-08-07 22:58
Duplicate of #178. Do you guys not get the rare bug report screen that links you to that bug? Anyway, thanks for uploading your game log

**Closed by Earthcomputer** 2021-08-07 22:58 UTC

**Comment by JackTGG** [comment] 2021-08-08 00:53
Hello trolle
