### ISSUE TITLE
Incompatible with Immersive Portals

### ISSUE THREAD

**Issue by Justsnoopy30** [Earthcomputer/multiconnect#236] opened 2021-08-28 21:59 UTC
Minecraft Version: 1.17.1
Multiconnect Version: Version 1.4.12 for Minecraft 1.17.1

The conflicting mod's GitHub: https://github.com/qouteall/ImmersivePortalsMod
Mixin conflict, log here:
`[02:25:05] [Render thread/WARN]: @Redirect conflict. Skipping multiconnect.1_12_2.mixins.json:MixinClientPlayerInteractionManager->@Redirect::cancelInteractBlockPacket(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by imm_ptl.mixins.json:client.block_manipulation.MixinClientPlayerInteractionManager->@Redirect::redirectSendPacketOnInteractBlock(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000 [02:25:06] [Render thread/FATAL]: Unreported exception thrown! org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[universe-loader-0.11.6.jar:0.9.4+mixin.0.8.2] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[universe-loader-0.11.6.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[universe-loader-0.11.6.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] at net.minecraft.class_634.method_11120(class_634.java:344) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_2678.method_11567(class_2678.java:100) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_2678.method_11054(class_2678.java:18) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_310.method_1523(class_310.java:1075) ~[intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-universe-fabric-loader-0.11.6-1.17.1.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [universe-loader-0.11.6.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:65) [universe-loader-0.11.6.jar:?] at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [universe-loader-0.11.6.jar:?] Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cancelInteractBlockPacket(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V in multiconnect.1_12_2.mixins.json:MixinClientPlayerInteractionManager failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap multiconnect-refmap.json at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2] ... 24 more`
And crash report generated:
`org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519) at net.minecraft.class_634.method_11120(class_634.java:344) at net.minecraft.class_2678.method_11567(class_2678.java:100) at net.minecraft.class_2678.method_11054(class_2678.java:18) at net.minecraft.class_2600.method_11072(class_2600.java:21) at net.minecraft.class_1255.method_18859(class_1255.java:151) at net.minecraft.class_4093.method_18859(class_4093.java:23) at net.minecraft.class_1255.method_16075(class_1255.java:125) at net.minecraft.class_1255.method_5383(class_1255.java:110) at net.minecraft.class_310.method_1523(class_310.java:1075) at net.minecraft.class_310.method_1514(class_310.java:728) at net.minecraft.client.main.Main.main(Main.java:217) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:567) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:65) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cancelInteractBlockPacket(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V in multiconnect.1_12_2.mixins.json:MixinClientPlayerInteractionManager failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap multiconnect-refmap.json at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ... 24 more`

**Comment by Justsnoopy30** [comment] 2021-08-28 22:00
Associated issue report: https://github.com/qouteall/ImmersivePortalsMod/issues/833

**Comment by Earthcomputer** [comment] 2021-08-28 23:26
Duplicate of #233, the next version will have `breaks` in fabric.mod.json.

**Comment by Earthcomputer** [comment] 2021-08-29 16:37
https://github.com/qouteall/ImmersivePortalsMod/pull/836

**Comment by Earthcomputer** [comment] 2021-08-30 14:48
This is fixed in v0.24-1.17 of immersive portals

**Closed by Earthcomputer** 2021-08-30 14:48 UTC

**Comment by luni3359** [comment] 2022-01-12 08:06
Does this mean that multiconnect is now compatible with the Immersive Portals mod? I'm asking because it's still listed as a conflicting mod.
https://github.com/Earthcomputer/multiconnect/blob/34a0ae8c863c8ccb56a164514cd9e20dab856ce9/src/main/resources/fabric.mod.json#L49-L52

**Comment by Earthcomputer** [comment] 2022-01-16 21:50
@luni3359 a conflicting pair of mods is one that causes issues together, but *not* one that is outright incompatible. Incompatible mods are in the "breaks" section.

**Comment by luni3359** [comment] 2022-01-17 06:26
I was wondering because Fabric won't open Minecraft if they're both added and I thought that was making it not work. Here's the error I'm getting:
![Screenshot from the Fabric loader](https://user-images.githubusercontent.com/16832398/149718277-86953976-654a-411d-9c6f-0f8722765c20.png)

**Comment by Earthcomputer** [comment] 2022-01-17 10:09
Looks like it's on their end: https://github.com/qouteall/ImmersivePortalsMod/blob/1.18/src/main/resources/fabric.mod.json#L48

**Comment by luni3359** [comment] 2022-01-17 16:12
Sorry about the confusion, I've made a comment on their repository addressing this issue.
