### ISSUE TITLE
[mod compat] textures are weird with optifabric

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [Earthcomputer/multiconnect#208] opened 2021-07-25 12:00 UTC
MC Version: 1.17.1
Optifine version: pre 29
viafabric/plus child pluigins (all latest versions as of writting this)
Krypton (Latest version as of writing)

in testing this is multiconnect and optifine ive only included viafabric/krypton just because (ive disabled the mods and tested without), blocks have the wrong textures when changing between servers that have different version (eg 1.17.1 --> 1.16.5) or by joining a server which has a lower version to the client to start with 

a temp fix for people with the same problem F3 + T fixes this and acts normal 

possible solution reloading resources when joining such server before hand (with a 2 second delay to allow for server side texture packs to apply if there are some)

**Comment by Earthcomputer** [comment] 2021-07-25 12:39
Duplicate of #94

**Closed by Earthcomputer** 2021-07-25 12:39 UTC
