### ISSUE TITLE
[1.19.3] Crash when opening creative inventory in singleplayer

### ISSUE THREAD

**Issue by Cheos137** [Earthcomputer/multiconnect#505] opened 2022-12-29 11:30 UTC
### Latest Version?

- [X] I confirm I have the latest version of multiconnect

### Description

When using multiconnect 1.19.3 1.6-beta.25, the game crashes when opening the creative inventory in singleplayer.
Full modlist + enabled resource packs (including some that alter creative inventory textures) can be found in the attached crash report/logfile.

### Log File

https://gist.github.com/Cheos137/ea0baf293695f03458904d8abf1fe49d#file-latest-log

### Crash Report (if applicable)

https://gist.github.com/Cheos137/ea0baf293695f03458904d8abf1fe49d#file-crash-2022-12-29_12-17-34-client-txt

**Comment by MorningXiao** [comment] 2023-01-10 05:21
same question

**Comment by PneumaticPiston** [comment] 2023-01-14 21:38
I as well have had the same issue

**Comment by xtexChooser** [comment] 2023-01-17 12:07
same

**Comment by AbidHasnineMahi** [comment] 2023-01-28 07:09
Try removing MiniHUD Mod.

**Comment by xtexChooser** [comment] 2023-01-28 08:51
no minihud, but Nvidia GTX-750Ti and InventoryHUD

**Comment by JaaiDead** [comment] 2023-01-29 06:43
its a problem with via verison and multiconnect combined

**Comment by JaaiDead** [comment] 2023-01-29 06:45
Duplicate of #505

**Closed** 2023-02-23 22:24 UTC
Labels: bug
