### ISSUE TITLE
[Feature Request] Show versions in server list even when it is compatible

### ISSUE THREAD

**Issue by DeSAiRePLYX** [Earthcomputer/multiconnect#235] opened 2021-08-28 15:48 UTC
For example im on 1.17.1 client and i add a vanilla 1.16.5 server to my list, i can connect no problem, but theres no direct way to know that the server is actually on 1.16.5

**Comment by Earthcomputer** [comment] 2021-08-28 15:50
Duplicate of #24

**Closed by Earthcomputer** 2021-08-28 15:50 UTC
