### ISSUE TITLE
Cannot force protocol version to 1.12.2

### ISSUE THREAD

**Issue by OrangeCatSeth** [Earthcomputer/multiconnect#97] opened 2020-09-09 08:15 UTC
The server is luckysb.org, forcing to protocol version 1.12.2 does not work, F3 shows server version 1.16.2.

**Comment by MineGame159** [comment] 2020-09-16 13:55
this

**Comment by Earthcomputer** [comment] 2020-09-16 20:54
I have identified the cause of this issue, and will be fixed in the next version, which I will release shortly. It was caused by a recent change made to ensure compatibility with ViaFabric's version detection.

**Closed** 2020-09-16 20:58 UTC

**Comment by Sneakometer** [comment] 2020-09-16 23:01
Still having the exact same issue using multiconnect 1.3.20.
However, switching to an older version (i tried 1.16.1, multiconnect 1.3.8) and then back to 1.16.3 temporarily fixes the bug.
Maybe has something todo with caching?
