### ISSUE TITLE
Unable to override client version as 1.12.2

### ISSUE THREAD

**Issue by MineGame159** [Earthcomputer/multiconnect#100] opened 2020-09-13 16:57 UTC
So when on 1.16.3 and I explicitly set the version to 1.12.2 and i try to connect to 1.12.2 servers (2b2tpvp.net, crystalpvp.cc, ...) it says "outdated server, server still running on 1.12.2".

**Comment by Earthcomputer** [comment] 2020-09-13 17:13
Duplicate of #97

**Closed by Earthcomputer** 2020-09-13 17:13 UTC
