### ISSUE TITLE
Connecting to server fails to request protocol version

### ISSUE THREAD

**Issue by Kichura** [Earthcomputer/multiconnect#107] opened 2020-10-11 15:50 UTC
When connecting to the server "cubecraft.net" using "auto" mode while it's added to the local server list or direct connected without setting version manually causes it to cancel the connection saying that the server protocol check has failed.

However when the server is edited with version set to a specific one instead of auto, It let's the player in without failing the protocol check.

**Comment by Earthcomputer** [comment] 2020-10-11 16:16
Duplicate of #17, please read that for the reasoning

**Closed by Earthcomputer** 2020-10-11 16:16 UTC
