### ISSUE TITLE
Feature request: Support modded registries when connecting to the current version

### ISSUE THREAD

**Issue by Gaming32** [Earthcomputer/multiconnect#340] opened 2022-04-12 15:00 UTC
I suggest that multiconnect allows the usage of modded registries when connecting to a server that is running on the same version as the client, in which case multiconnect already does nothing (there's nothing to do).

**Comment by lenrik1589** [comment] 2022-04-12 16:05
I kind of see why that could be of use, but then, why not have a separate instance for connecting to a modded server, where you could install more mods that are interacting with server, and if you already have those client-side mods that are required server-side, why bother connecting to older version: it is very much possible that mod dev changed their networking between the versions.

**Comment by Gaming32** [comment] 2022-04-12 16:08
Here's why: I use many client-side mods, such as Tweakeroo and Xaero's *Map. I often forget to remove multiconnect when connecting to modded servers, and so I load into Minecraft then go to connect and am unable to. I then have to remove multiconnect and restart Minecraft. Minecraft takes a decent amount of time to load, and it's just an inconvenience since I also forget to add multiconnect back when I'm done with the modded server.

**Comment by Username404-59** [comment] 2022-04-12 23:00
> Minecraft takes a decent amount of time to load

I'd suggest adding LazyDFU if you don't have it already.

**Comment by Gaming32** [comment] 2022-04-12 23:26
I've been meaning to get it. However, that's besides the point. The point is that multiconnect blocking perfectly valid same-version things when connecting to a server with the same version is an unnecessary hassle.

**Comment by Earthcomputer** [comment] 2022-04-12 23:39
Duplicate of #226

**Closed by Earthcomputer** 2022-04-12 23:39 UTC
