### ISSUE TITLE
Bug on 1.11 (other version is not tested) on funcraft.net

### ISSUE THREAD

**Issue by Finoway** [Earthcomputer/multiconnect#122] opened 2020-11-02 18:50 UTC
Hi, I was asking the funcraft staff and they told me that a multiconnect style mod is allowed if it doesn't allow cheat so there's no problem.

I went to do a hikabrain on the server but while doing the game I died and I ended up with an error that will be written below and I couldn't move at all and I was kicked out of the game for "Flying is not enable on this server".

**Error:**
```
[18:24:32] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 11 on entity class_1452['Pig'/26997, l='ClientLevel', x=14.23, y=55.42, z=3.32]: old=0(class java.lang.Byte), new=0.0(class java.lang.Float)
	at net.minecraft.class_2945.method_12785(class_2945.java:241) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_2945.method_12779(class_2945.java:228) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_634.method_11093(class_634.java:568) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_634.applyPendingEntityTrackerValues(class_634.java:5470) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_634.handler$zeo000$onOnMobSpawn(class_634.java:5438) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_634.method_11138(class_634.java:941) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_2610.method_11217(class_2610.java:90) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_2610.method_11054(class_2610.java:14) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:990) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.3-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

[18:24:40] [main/WARN]: Entity class_1452['Pig'/26997, l='ClientLevel', x=14.23, y=55.42, z=3.32] does not have attribute minecraft:generic.attack_speed

```

**Video with the bug:** https://youtu.be/E7q2v6jgbBc

**Mods:**  multiconnect-1.3.32.jar

**Comment by Earthcomputer** [comment] 2020-11-02 21:26
Please try on 1.11.2 and 1.10 and let me know if it works. Iirc the reason there is a 1.11.2 is because the older 1.11 versions had issues like this.

**Comment by Finoway** [comment] 2020-11-03 11:14
It's same

Youtube link: https://youtu.be/a9yf7U1ni2k
Log link: https://paste.ee/p/C9kXT

**Comment by Finoway** [comment] 2020-11-03 11:52
Hi, I just thought there is an autorespawn on the server I wonder if the bug where I can't move anymore comes from that and I just tested in 1.10 it's the same.

**Comment by Kichura** [comment] 2020-11-04 18:37
Tried reproducing this issue and confirmed on 1.11 protocol.

Versions used: 1.16.4, 1.3.33.

**Comment by Kichura** [comment] 2020-11-04 18:43
Also managed to reproduce this issue on 1.11.2 - 1.10 including all 1.9.x versions as multiconnect is providing through the time of this comment.

**Comment by LaVache-FR** [comment] 2020-11-18 20:23
hi I have exactly the same problem on the **Funcraft.net** server, I tested on 1.9x 1.10x 1.11x versions, I still have the same problem I remain blocked in the air is my trenble camera

**Comment by NOcturnais** [comment] 2020-11-18 20:37
la commu vache on est ici

**Comment by Earthcomputer** [comment] 2020-11-18 20:39
@NOcturnais please keep conversation in English so I can understand.

**Comment by H4ckeurr** [comment] 2020-11-18 20:53
Tried reproducing this issue on funcraft and can confirm it does happens, tried 1.9, 1.10 and 1.11

**Comment by UwUDev** [comment] 2020-11-18 21:03
Same issue here :/

**Comment by xTrM-EN** [comment] 2020-11-18 21:08
Can reproduce on 1.9.X through 1.11.0 using latest version @ the time of this comment.

**Comment by KaitoMomota** [comment] 2020-11-19 05:18
i think that i like cheese but i don't know if its true or not can you make a boolean that will return me the result so i can know if i like it or not ? it is a bug who should be fixed §!!§§!!

**Comment by Earthcomputer** [comment] 2020-11-19 08:47
Locking due to spam. It will be fixed in the next round of bugfixes.

**Comment by Earthcomputer** [comment] 2021-06-01 01:17
Field 11 for pigs is a byte in 1.11.2, but the server is sending a float. Looks like the server is sending invalid data.

**Closed by Earthcomputer** 2021-06-01 01:17 UTC
Labels: bug, priority: medium
