### ISSUE TITLE
[Bug] lighting and chunk loading problems in 1.8 - 1.11.2 versions

### ISSUE THREAD

**Issue by mathmakgakpak** [Earthcomputer/multiconnect#237] opened 2021-08-29 19:25 UTC
https://youtu.be/QRmOtP2zbYI
[2021-08-29-7.log](https://github.com/Earthcomputer/multiconnect/files/7072975/2021-08-29-7.log)

**Comment by Earthcomputer** [comment] 2021-08-29 23:41
After some investigation, this appears to be a duplicate of #128

**Closed by Earthcomputer** 2021-08-29 23:41 UTC
