### ISSUE TITLE
Player names are the wrong color using 1.12.2 protocol and earlier.

### ISSUE THREAD

**Issue by OrangeCatSeth** [Earthcomputer/multiconnect#186] opened 2021-06-19 01:36 UTC
Server is bridger.land
![2021-06-18_20 33 30](https://user-images.githubusercontent.com/24788083/122627387-a81a1f00-d074-11eb-9b87-863af347e803.png)
![2021-06-18_20 32 53](https://user-images.githubusercontent.com/24788083/122627394-aea89680-d074-11eb-88d1-c3b65739c667.png)

**Comment by OrangeCatSeth** [comment] 2021-06-19 01:43
Vanilla 1.12.2 client
![2021-06-18_20 42 45](https://user-images.githubusercontent.com/24788083/122627551-cb919980-d075-11eb-9357-ba9a5fd02516.png)

**Comment by Earthcomputer** [comment] 2021-06-19 08:46
Duplicate of #133

**Closed by Earthcomputer** 2021-06-19 08:46 UTC
