### ISSUE TITLE
[1.19] -> [1.12.2] Error translating flower pots

### ISSUE THREAD

**Issue by Packsolite** [Earthcomputer/multiconnect#377] opened 2022-06-16 00:31 UTC
Entering any 1.12.X server with a flowerpot nearby will disconnect you for the following reason:
![image](https://user-images.githubusercontent.com/102829507/173964299-9bbc2596-4317-4d33-92d2-40ede5f8bb75.png)

Multiconnect version is latest [1.6-beta.14](https://github.com/Earthcomputer/multiconnect/commit/ee5cbf489d9d03e9cd12b43e26d75e367666d973)

You can test this on the server `smashmc.eu` by forcing 1.12.2.

Log:
```
[02:24:52] [Render thread/INFO]: Connecting to smashmc.eu, 25565
[02:24:52] [Server Connector #19/INFO]: Protocol version forced to 340 (1.12.2)
[02:24:52] [Netty Client IO #10/WARN]: Ambiguity between arguments [cfind, --keep-searching] and [cfind, filter] with inputs: [--keep-searching]
[02:24:52] [Render thread/WARN]: Ambiguity between arguments [cfind, --keep-searching] and [cfind, filter] with inputs: [--keep-searching]
[02:24:52] [Netty Client IO #10/ERROR]: !!!!!!!! Unexpected packet error, please upload this error to https://github.com/Earthcomputer/multiconnect/issues !!!!!!!!
[02:24:52] [Netty Client IO #10/ERROR]: It may be helpful if you also provide the server IP, but you are not obliged to do this.
[02:24:52] [Netty Client IO #10/ERROR]: Minecraft version: 1.19
[02:24:52] [Netty Client IO #10/ERROR]: multiconnect version: 1.6-beta.13-12-gee5cbf48
[02:24:52] [Netty Client IO #10/ERROR]: Server version: 340 (1.12.2)
[02:24:52] [Netty Client IO #10/ERROR]: Server brand: Waterfall <- NachoSpigot
[02:24:52] [Netty Client IO #10/ERROR]: Direction: inbound
[02:24:52] [Netty Client IO #10/ERROR]: Compressed packet data: H4sIAAAAAAAA/+NkYBA/IMPAmM3KxcDAzMDiWZKay8DAoMDMwFjFABTmYGDKTGEQyc3MS00uSkwrsUrLyS9PLYovyC8BKqkEKmUH0hVAOh6o2yWxJJEBBACub5JxVwAAAA==
[02:24:52] [Netty Client IO #10/ERROR]: Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown type minecraft:flower_pot in net.minecraft.class_1208$$Lambda$1117/0x0000000800595d78@184509ba 
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Unknown type minecraft:flower_pot in net.minecraft.class_1208$$Lambda$1117/0x0000000800595d78@184509ba 
	at net.minecraft.class_3553.method_15475(class_3553.java:34) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at java.util.function.Function.lambda$compose$0(Function.java:68) ~[?:?]
	at java.util.function.Function.lambda$compose$0(Function.java:68) ~[?:?]
	at com.mojang.datafixers.FunctionType$Instance.lambda$first$1(FunctionType.java:81) ~[datafixerupper-5.0.28.jar:?]
	at java.util.function.Function.lambda$compose$0(Function.java:68) ~[?:?]
	at java.util.function.Function.lambda$compose$0(Function.java:68) ~[?:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.functions.Comp.lambda$eval$5(Comp.java:69) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.capWrite(Type.java:167) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.lambda$readAndWrite$9(Type.java:159) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.types.Type.readAndWrite(Type.java:158) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:84) ~[datafixerupper-5.0.28.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketIntrinsics.datafix(PacketIntrinsics.java:63) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at net.earthcomputer.multiconnect.generated.Protocol_1_12_2.translateSPacketBlockEntityUpdate_1_17_1(Protocol_1_12_2.java:30547) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$0(MulticonnectClientboundTranslator.java:45) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:226) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$1(MulticonnectClientboundTranslator.java:44) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at net.earthcomputer.multiconnect.impl.PacketSystem$Internals.submitTranslationTask(PacketSystem.java:302) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.lambda$decode$4(MulticonnectClientboundTranslator.java:43) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils.wrapInErrorHandler(DebugUtils.java:226) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at net.earthcomputer.multiconnect.protocols.generic.MulticonnectClientboundTranslator.decode(MulticonnectClientboundTranslator.java:37) ~[multiconnect-1.6-beta.13-12-gee5cbf48.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:?]
	... 36 more
[02:24:52] [Render thread/INFO]: New minimap session initialized!
[02:24:52] [Render thread/INFO]: New world map session initialized!
[02:24:52] [Render thread/INFO]: Started 8 worker threads
[02:24:52] [Render thread/INFO]: Minimap session finalized.
[02:24:52] [Render thread/INFO]: Finalizing world map session...
[02:24:52] [Thread-1/INFO]: World map force-cleaned!
[02:24:52] [Render thread/INFO]: World map session finalized.
[02:24:52] [Render thread/INFO]: Stopping worker threads

```

**Comment by Earthcomputer** [comment] 2022-06-23 16:19
Duplicate of #374

**Closed by Earthcomputer** 2022-06-23 16:19 UTC
