### ISSUE TITLE
Multiconnect detecting wrong server version on 1.16.3

### ISSUE THREAD

**Issue by Sneakometer** [Earthcomputer/multiconnect#103] opened 2020-09-16 15:59 UTC
Hello, i updated fabric from 1.16.2 to 1.16.3 with latest multiconnect, but since i can't join a 1.12.2 server.
I get this error:
![Screenshot_1](https://user-images.githubusercontent.com/50603525/93361802-8c63bd00-f845-11ea-922d-e31b9d64d82b.png)

The server i want to connect to is running 1.12.2 paper, but uses ViaVersion to support Minecraft up to 1.15.2, but not 1.16.3.

In the logs, i found this:
```
[17:54:50] [main/INFO]: Connecting to myserver.com., 25565
[17:54:50] [Server Connector #3/INFO]: Discovered server protocol: 751 (1.16.2)
```
But clearly the server is not 1.16.2

When using 1.16.2 with multiconnect, everything works just fine.

**Comment by Sneakometer** [comment] 2020-09-16 16:01
It may be related to https://github.com/Earthcomputer/multiconnect/issues/97, but this issues does NOT affect explicit 1.12.2 servers.

**Comment by Kichura** [comment] 2020-09-16 19:14
Reproduced this on a private server that has waterfall (1.8.x - 1.16.3 support) installed and confirmed as in: "Outdated Server!, I'm still on {0}".

**Comment by Earthcomputer** [comment] 2020-09-16 20:54
Closing as duplicate of #97, as they have the same cause (the other issue just has a more specific than necessary title)

**Comment by Sneakometer** [comment] 2020-09-16 22:53
It's still not fixed in release 1.3.20.

**Comment by Earthcomputer** [comment] 2020-09-16 22:56
Okay, can you provide me with a server it doesn't work on so I can test this?

**Comment by Sneakometer** [comment] 2020-09-16 23:04
E.g. varoxcraft.de

**Comment by Earthcomputer** [comment] 2020-09-17 23:02
Actually fixed now :P

**Closed by Earthcomputer** 2020-09-17 23:02 UTC
