### ISSUE TITLE
I have no idea what's happening

### ISSUE THREAD

**Issue by lenrik1589** [Earthcomputer/multiconnect#84] opened 2020-07-26 00:00 UTC
https://paste.ee/p/Vwmgh
I was just getting some bedrock with other guys on PT and it suddenly started kicking me
it started happening right after i died, pressed respawn and while i was respawning server restarted

**Comment by Earthcomputer** [comment] 2020-07-26 08:18
That's weird, I will look into it

**Comment by Earthcomputer** [comment] 2020-07-29 08:19
Cannot reproduce

**Comment by Earthcomputer** [comment] 2020-07-29 08:27
If it's a mod incompatibility, try and find out which mod it is

**Comment by lenrik1589** [comment] 2020-08-01 08:20
oh, it resolved itself? i think? and i didn't change anything from the last time.

**Comment by lenrik1589** [comment] 2020-08-01 09:18
Sorry for inconvenience.

**Comment by lenrik1589** [comment] 2020-08-03 23:38
https://paste.ee/p/NA04f 
that happened again again, no idea why, while connecting to carpet 1.12.2 server

**Comment by Earthcomputer** [comment] 2020-08-04 00:01
When it stopped happening, did you uninstall fabric API by any chance?

**Comment by lenrik1589** [comment] 2020-08-04 00:06
no

**Comment by lenrik1589** [comment] 2020-08-04 00:08
huh, it connected rn, after i stayed in 1.16.1 server for a while and tried again

**Comment by lenrik1589** [comment] 2020-08-04 00:25
oh, it might have happened after i canceled connection process

**Comment by lenrik1589** [comment] 2020-08-04 00:29
it might be not finishing all the registry manipulation and just getting stopped by minecraft itself so that the registry is in unfinished state and then on next connection it tries to overrite already existing thing?

**Comment by Earthcomputer** [comment] 2020-08-04 07:06
That definitely sounds plausible.

**Comment by Earthcomputer** [comment] 2020-08-31 11:07
I believe this is a duplicate of #91. Yes, I know that bug report is newer, but it is of higher quality so I'll keep that one and close this.

**Closed by Earthcomputer** 2020-08-31 11:07 UTC

**Comment by lenrik1589** [comment] 2020-09-01 14:09
Well, the exception I was getting doesn't involve SinglePlayer and didn't get consistently fixed by restarting client, the only info I had was that long random error list I've sent, sorry for inconvenience.

**Comment by Earthcomputer** [comment] 2020-09-01 14:10
It fits into the more general category of problems related to cancelling a connection to a server

**Comment by lenrik1589** [comment] 2020-09-01 14:15
It doesn't happen every time on stopping connection process( I think, will test when home) very basic fix I would think of is to force loading finishing or something like that, if it really  only happens on aborted connection
