### ISSUE TITLE
[1.17.1] -> [1.12.2] Beds show up incorrectly, water reflow doesn't update, gravel fall desync, tnt+other desync

### ISSUE THREAD

**Issue by sudofox** [Earthcomputer/multiconnect#257] opened 2021-10-15 19:12 UTC
Observed on the world's worst Minecraft server. I'm wondering of some of these have a common cause.

- When placing a bed, it glitches for a second and then only one part of the bed shows up -- sometimes even in the wrong color (white).
- When blowing up TNT, the explosion pattern seems to be incorrect, leaving lots of ghost blocks. Right clicking on them doesn't make the ghost blocks go away, and sometimes the TNT just kinda floats there client-side.
- When gravel is destroyed, sometimes it doesn't actually destroy properly and that leaves ghost blocks.
- When water reflows due to block changes, it doesn't seem to update client-side -- you can drown or get flicked around by anti-cheat thinking you're using movement hacks.
- Other desync issues -- sometimes entire chunks disappear vertically, either partially or all the way down past bedrock and i have to relog or "place" blocks in the spot to get the correct block back.

**Comment by Earthcomputer** [comment] 2021-10-17 16:56
Ah, that was the duplicate, I couldn't find so I didn't label it. And yes I've been working on the translation rewrite. If I can't get that done by 1.18 then I will fix this and other bugs with the current system and update the current system to 1.18.

The bug may be common to reproduce under certain conditions but I haven't found those conditions yet. That's why it's not fixed. Every time I try to log in to a server people claim it happens on, I have some issue or other preventing me from being able to test it. For example that Russian server has some login system in Russian that I can't figure out because it's in Russian.

**Comment by Earthcomputer** [comment] 2021-10-17 16:56
Closing as duplicate, though.

**Closed by Earthcomputer** 2021-10-17 16:56 UTC
