### ISSUE TITLE
Glitchy chunk loading when using 1.9.2 protocol and below.

### ISSUE THREAD

**Issue by OrangeCatSeth** [Earthcomputer/multiconnect#120] opened 2020-10-30 01:34 UTC
This occurs in the lobby on play.minehut.gg, not sure if this occurs elsewhere.
I also tested vanilla 1.9, to rule out server side issues.

1.9.2 protocol: https://streamable.com/0tilhl
1.9.4 protocol: https://streamable.com/0czbpl

**Comment by mygizli04** [comment] 2020-10-30 06:28
Minehut has all 3 via plugins installed, you should use your native client version

**Comment by OrangeCatSeth** [comment] 2020-10-30 07:53
I know, but the point is differing behavior from a vanilla 1.9 client

**Comment by Earthcomputer** [comment] 2020-10-30 19:51
Any difference from a vanilla client is an issue.
This looks like an issue I've seen before, and fixed on the 1.8 branch. I'll test it now.

**Comment by Earthcomputer** [comment] 2020-10-30 20:00
Yes, I confirmed it to be the same issue. This happens when chunks containing bed blocks are loaded with the 1.9.2 protocol or below. It might be severe enough to release a fix for before I release the 1.8 protocol.

**Closed** 2020-10-30 20:04 UTC
Labels: bug, priority: high
